version: '3'
networks:
  app-tier:
    driver: bridge

services:
    myapp:
      image: wildfly-app
      ports:
        - 8080:8080
      depends_on:
        - db
      networks:
        - app-tier
    db:
      image: bitnami/postgresql
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=portal
        - POSTGRES_DATABASE=cadastros
        - POSTGRES_DATABASE=venda
        - POSTGRES_DATABASE=relatorios
      networks:
        - app-tier
